#!/bin/bash

set -o pipefail
#set -x

declare -r SCRIPT='ams'
# shellcheck disable=SC2155
declare -r DIR="$(dirname "${BASH_SOURCE[0]}")"

# shellcheck disable=SC1090
. "${DIR}/commons"
# shellcheck disable=SC1090
. "${DIR}/git_functions"
# shellcheck disable=SC1090
. "${DIR}/gitlab_api"

# shellcheck disable=SC2155
declare WORKING_DIR="$(readlink -f ".")"
(( $# == 0 )) \
  && exception "Missing command, enter '${SCRIPT} help' to display usage" 2
while (( $# > 0 )); do
  case "${1}" in
    -w|--working-dir)
      WORKING_DIR="$(readlink -f "${2}")"
      [[ -d "${WORKING_DIR}" ]] \
        || exception 'WORKING_DIR not found'
      shift; shift ;;
    help)
      print_usage
      exit
      ;;
    collect|distribute|evaluate|measure)
      declare -r CMD="${1}"
      shift
      # shellcheck disable=SC1090
      . "${DIR}/${CMD}"
      exit $?
      ;;
    *)
      exception "Invalid command '${1}', enter '${SCRIPT} help' to display usage" 2
      ;;
  esac
done
