#!/bin/bash

declare SHIELDS='https://img.shields.io/static/v1'
declare DEFAULT_COLOR='inactive'

# init pathnames to badges
badge_init() {
  local badge_name="${1}"
  local badge_default="${2}" #opt
  badge_generate "${badge_name}" "${badge_default:--}"
  # printf '' ... FIXME - Print badge URL
}

# % to colors
percent_to_color() {
  declare color='brightgreen'
  declare perc="${1%\%}"
  (( 10#$perc < 85 )) \
    && color='green'
  (( 10#$perc < 70 )) \
    && color='yellow'
  (( 10#$perc < 55 )) \
    && color='orange'
  (( 10#$perc < 45 )) \
    && color='red'
  printf -- '%s\n' "${color}"
}

fraction_to_color() {
  if [[ "${1}" == */0 ]]; then
    printf '%s\n' "${DEFAULT_COLOR}"
    return 1
  fi
  percent_to_color "$(( 100 * $1 ))"
}

# URL encoding
url_encode() {
  jq -Rr @uri <<< "${1}"
}

# generate badge
badge_generate() {
  # required
  local label="${1:-}"
  local value="${2:-}"
  [[ -z "${label}" || -z "${value}" ]] \
    && echo 'Missing badge label or value' >&2 \
    && return 2
  # optional
  local color="${3:-}"
  local file_name="${4:-}"
  local link="${5:-}"
  local title="${6:-}"
  # auto color
  [[ -z "${color}" ]] \
    && case "${value}" in
      n/a) color="${DEFAULT_COLOR}" ;;
      */*) color="$(fraction_to_color "${value}")" ;;
      *%) color="$(percent_to_color "${value%\%}")" ;;
      *) color="${DEFAULT_COLOR}"
    esac
  # default badge name is "badge-[ci job name]-[normalized label]"
  # normalized label: spaces to dashes, to lowercase
  [[ -z "${file_name}" ]] \
    && file_name="${label// /-}" \
    && file_name="badge-${CI_JOB_NAME:-local}-${file_name,,}"
  # generate shileds.io badge
  WORKING_DIR="${WORKING_DIR:-.}"
  local dest="${RESULTS:-${WORKING_DIR}/.results}/${file_name}.svg"
  curl -so "${dest}" "${SHIELDS}?label=$(url_encode "${label}")&message=$(url_encode "${value}")&color=${color}"
  # always add link element with or without href
  # always cause of title not working only in svg, it needs to be in some element like <a>
  [[ -n "${link}" ]] \
    && link="href=\"${link}\""
  sed -Ei "s~(<svg[^>]+>)(.*)(</svg>)~\1<a ${link}>\2</a>\3~" "${dest}"
  # update title
  [[ -n "${title}" ]] \
    && sed -Ei "s~<title>.*</title>~<title>${title}</title>~" "${dest}"
  return
}
