#!/bin/bash

declare SHIELDS='https://img.shields.io/static/v1'
declare DEFAULT_COLOR='gray'

# init pathnames to badges
badge_init() {
  local badge_name="${1}"
  local badge_default="${2}" #opt
  local badge_color="${DEFAULT_COLOR}"
  badge_generate "${badge_name}" "${badge_default:--}" "${badge_color}"
  # printf '' ... FIXME - Print badge URL
}

# % to colors
percent_to_color() {
  declare color='brightgreen'
  declare perc="${1}"
  (( perc < 85 )) \
    && color='green'
  (( perc < 70 )) \
    && color='yellow'
  (( perc < 55 )) \
    && color='orange'
  (( perc < 45 )) \
    && color='red'
  printf -- '%s\n' "${color}"
}

fraction_to_color() {
  if [[ "${1}" == */0 ]]; then
    printf '%s\n' "${DEFAULT_COLOR}"
    return 1
  fi
  percent_to_color "$(( 100 * $1 ))"
}

# URL encoding
url_encode() {
  jq -Rr @uri <<< "${1}"
}

# generate badge
badge_generate() {
  local badge_name="${1}"
  local ci_job="${CI_JOB_NAME:-local}"
  local badge_file="${badge_name// /-}"
  badge_file="${RESULTS:${WORKING_DIR}/.results}/badge-${ci_job}-${badge_file,,}.svg"
  local badge_label
  badge_label="$( url_encode "${badge_name}" )"
  local badge_value
  badge_value="$( url_encode "${2}" )"
  local badge_color
  [[ -z "${3}" ]] \
    && case "${badge_value}" in
      n/a) badge_color="${DEFAULT_COLOR}";;
      */*) badge_color="$( fraction_to_color "${2}" )";;
      *%) badge_color="$( percent_to_color "${2%\%}" )";;
      *) badge_color="${DEFAULT_COLOR}"
    esac
  curl -so "${badge_file}" "${SHIELDS}?label=${badge_label}&message=${badge_value}&color=${badge_color}"
}
