#!/bin/bash

set -o pipefail
#set -x

declare -r SCRIPT='ca'
# shellcheck disable=SC2155
declare -r DIR="$(dirname "${BASH_SOURCE[0]}")"
declare -r CMD="${1}"
declare -r USAGE="usage: ${SCRIPT} <command> [<args>]

These are common ${SCRIPT} commands used in various situations:

   distribute        Create or update user repositories with files from source project.

   evaluate          Verify Java project and generate badges into README.

   help              Display this usage.

   measure           Compute software similarities between projects using Moss script.
"

# shellcheck disable=SC1090
. "${DIR}/commons"
# shellcheck disable=SC1090
. "${DIR}/git_functions"
# shellcheck disable=SC1090
. "${DIR}/gitlab_api"

case "${CMD}" in
  help)
    format_usage <<< "${USAGE}"
    ;;
  distribute|evaluate|measure)
    shift
    # shellcheck disable=SC1090
    . "${DIR}/${CMD}"
    ;;
  "")
    exception "Missing command, enter '${SCRIPT} help' to display usage" 2
    ;;
  *)
    exception "Invalid command '${CMD}', enter '${SCRIPT} help' to display usage" 2
    ;;
esac
