#!/bin/bash

set -o pipefail
#set -x

declare -r SCRIPT='ca'
# shellcheck disable=SC2155
declare -r DIR="$(dirname "${BASH_SOURCE[0]}")"
declare -r USAGE="usage: ${SCRIPT} [-w] <command> [<args>]

    -w, --working-dir WORKING_DIR
           Run as if ${SCRIPT} was started in WORKING_DIR instead of the current working directory.

These are common ${SCRIPT} commands used in various situations:

   distribute        Create or update user repositories with files from source project.
   evaluate          Verify Java project and generate badges into README.
   help              Display this usage.
   measure           Compute software similarities between projects using Moss script.
"

# shellcheck disable=SC1090
. "${DIR}/commons"
# shellcheck disable=SC1090
. "${DIR}/git_functions"
# shellcheck disable=SC1090
. "${DIR}/gitlab_api"

# shellcheck disable=SC2155
declare WORKING_DIR="$(readlink -f ".")"
while (( $# > 0 )); do
  case "${1}" in
    -w|--working-dir)
      WORKING_DIR="$(readlink -f "${2}")"
      [[ -d "${WORKING_DIR}" ]] \
        || exception 'WORKING_DIR not found'
      shift; shift ;;
    help)
      fmt -tw "$(tput cols)" <<< "${USAGE}"
      exit
      ;;
    distribute|evaluate|measure)
      declare -r CMD="${1}"
      shift
      # shellcheck disable=SC1090
      . "${DIR}/${CMD}"
      exit $?
      ;;
    "")
      exception "Missing command, enter '${SCRIPT} help' to display usage" 2
      ;;
    *)
      exception "Invalid command '${1}', enter '${SCRIPT} help' to display usage" 2
      ;;
  esac
done
