#!/usr/bin/env bash

declare MSG_OPENED='false'

clear_stdin() {
  while read -r -t 0; do read -r; done
}
msg_start() {
  [[ "${MSG_OPENED}" == 'true' ]] \
    && exception 'Message already started'
  MSG_OPENED='true'
  printf -- '%s ... ' "$@" >&2
}
msg_end() {
  declare -r close_message=${1:-DONE}
  [[ "${MSG_OPENED}" = 'false' ]] \
    && exception 'Message not started'
  MSG_OPENED='false'
  printf -- '[ %s ]\n' "${close_message}" >&2
}
confirm() {
  printf -- '%s [YES/No] ' "${1:-'Are you sure?'}" >&2
  clear_stdin
  read -r
  [[ "${REPLY}" =~ ^[Yy]([Ee][Ss])?$ || -z "${REPLY}" ]] \
    && return 0
  [[ "${REPLY}" =~ ^[Nn][Oo]?$ ]] \
    && return 1
  confirm 'Type'
}
prompt() {
  declare -r message="${1:-Enter value}"
  declare -r silent="${2}"
  printf -- '%s: ' "${message}" >&2
  clear_stdin
  # silent user input (e.g. for password)
  if [[ "${silent}" == 'silent' ]]; then
    read -rs
  else
    read -r
  fi
  [[ -n "${REPLY}" ]] \
    && return 0
  prompt "${message}"
}
exception() {
  declare -r message="${1:-Unknown exception}"
  declare -ri code=${2:-1}
  (( code == 1 )) \
    && printf -- '%s in %s() [ #%d ]\n' "${message}" "${FUNCNAME[1]}" "${code}" >&2 \
    || printf -- '%s [ #%d ]\n' "${message}" "${code}" >&2
  exit "${code}"
}
warning() {
  declare -r message="${1:-Unknown warning}"
  printf -- '%s\n' "${message}" >&2
}
check_x() {
  [[ -x "${1}" ]] \
    || chmod +x "${1}"
}
print_usage() {
  declare out
  declare cmd="${CMD}"
  [[ -n "${CMD}" ]] \
    && cmd="-${cmd}"
  # shellcheck disable=SC2155
  declare usage="$(get_md_section "## SYNOPSIS" < "${DIR}/documentation/${SCRIPT}${cmd}.md")"
  [[ -n "${usage}" ]] \
    && out="usage: ${usage}"
  # shellcheck disable=SC2155
  declare commands="$(get_md_section "## COMMANDS" < "${DIR}/documentation/${SCRIPT}${cmd}.md")"
  [[ -n "${commands}" ]] \
    && out="${out}"$'\n'"${commands}"
  # shellcheck disable=SC2155
  declare options="$(get_md_section "## OPTIONS" < "${DIR}/documentation/${SCRIPT}${cmd}.md")"
  # shellcheck disable=SC2001
  [[ -n "${options}" ]] \
    && out="${out}"$'\n'"$(sed 's/^/    /g' <<< "${options}")"
  fmt -w "$(tput cols)" <<< "${out}"
}
check_command() {
  for cmd in "${@}"; do
    command -v "${cmd}" >/dev/null 2>&1 \
      || exception "Command ${cmd} not found"
  done
}
get_md_section() {
  declare -r section="${1}"
  awk -v section="${section}" '
    BEGIN {
      out = 0
    }
    /^##/ {
      if ($0 == section) {
        out = 1; next
      }
      out = 0
    }
    {
      if (out == 1) {
        print
      }
    }' \
    | sed 's/`//g'
}
