#!/bin/bash

evaluate() {

  mkdir -p "${RESULTS}"
  curl -o "${RESULTS}/compile.svg" 'https://img.shields.io/badge/Compile-failed-critical'
  curl -o "${RESULTS}/checkstyle.svg" 'https://img.shields.io/badge/Code%20Style-n/a-gray'
  curl -o "${RESULTS}/test.svg" 'https://img.shields.io/badge/Tests%20Passed-0/0-gray'

  mvn -f "${POM}" compile > "${RESULTS}/compile.log" 2>&1 \
    || exit 0
  curl -o "${RESULTS}/compile.svg" 'https://img.shields.io/badge/Compile-passed-success'

  # shellcheck disable=SC2155
  declare -r tmppom="$(mktemp -d)/checkstyle-pom.xml"
  declare -r src='src/main'

  cat << EOD > "${tmppom}"
  <project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>InternetGuru</groupId>
    <artifactId>java-checkstyle</artifactId>
    <version>1</version>
    <properties>
      <maven.compiler.source>1.8</maven.compiler.source>
      <maven.compiler.target>1.8</maven.compiler.target>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
      <sourceDirectory>${WORKING_DIR}/${src}</sourceDirectory>
      <testSourceDirectory>${WORKING_DIR}/src/test</testSourceDirectory>
      <pluginManagement>
        <plugins>
           <plugin>
             <groupId>org.apache.maven.plugins</groupId>
             <artifactId>maven-checkstyle-plugin</artifactId>
             <version>3.1.1</version>
             <configuration>
               <configLocation>google_checks.xml</configLocation>
               <encoding>UTF-8</encoding>
               <consoleOutput>true</consoleOutput>
               <failsOnError>true</failsOnError>
               <linkXRef>false</linkXRef>
             </configuration>
             <executions>
               <execution>
                 <id>validate</id>
                 <phase>validate</phase>
                 <goals>
                   <goal>check</goal>
                 </goals>
               </execution>
             </executions>
           </plugin>
        </plugins>
      </pluginManagement>
    </build>
  </project>
EOD

  # run checkstyle and save warnings and errors into log
  mvn -f "${tmppom}" checkstyle:check | grep '^\[\(WARN\|ERROR\)' > "${RESULTS}/checkstyle.log"
  [[ ${PIPESTATUS[0]} != 0 ]] \
    && exit 1

  # shellcheck disable=SC2155
  declare -ri errs=$(cut -d" " -f2 < "${RESULTS}/checkstyle.log" | sort -ut: -k1,2 | wc -l)
  # shellcheck disable=SC2155
  declare -ri lines=$(find ${src} -name '*.java' -exec cat {} + | wc -l)
  declare -i perc=100
  (( errs > 0 )) \
    && (( perc = 99 - errs * 100 / lines ))

  declare color='brightgreen'
  (( perc < 85 )) \
    && color='green'
  (( perc < 70 )) \
    && color='yellow'
  (( perc < 55 )) \
    && color='orange'
  (( perc < 45 )) \
    && color='red'

  curl -o "${RESULTS}/checkstyle.svg" "https://img.shields.io/badge/Code%20Style-${perc}%20%25-${color}"

  declare test_color='success'
  mvn -f "${POM}" test > "${RESULTS}/test.log" 2>&1 \
    || test_color='critical'
  # shellcheck disable=SC2155
  declare -r summary=$(grep 'Tests run:' "${RESULTS}/test.log" | head -n1)
  # shellcheck disable=SC2155
  declare -ri runs=$(tr -d ',' <<< "${summary}" | cut -d' ' -f4)
  # shellcheck disable=SC2155
  declare -ri failures=$(tr -d ',' <<< "${summary}" | cut -d' ' -f6)
  declare -ri passed=$((runs - failures))
  curl -o "${RESULTS}/test.svg" "https://img.shields.io/badge/Tests%20Passed-${passed}/${runs}-${test_color}"
}

declare -r RESULTS=".results"
declare -r POM="${WORKING_DIR}/pom.xml"

evaluate
