#!/usr/bin/env bash

for file in "${CHANGED_FILES[@]}"; do
  io_tests "java \${FILE_PATH}" "${file}"
  if grep -q "static void main" "${WORKING_DIR}/${file}"; then
    java "${WORKING_DIR}/${file}"
  fi
done
