#!/usr/bin/env bash

main() {
  declare -r RESULTS="${WORKING_DIR}/.results"
  declare -r BADGES_TXT="${RESULTS}/badges.txt"
  declare -r GENERATED_TXT="${RESULTS}/generated.txt"

  mkdir -p "${RESULTS}"

  # shellcheck disable=SC2034
  mapfile -t CHANGED_FILES < <(
    git -C "${WORKING_DIR}" diff HEAD..HEAD~1 --name-only 2>/dev/null \
      | grep -E "${ACADEMY_EDITABLE:-*.*}"
  )

  # shellcheck disable=SC1090
  [[ -f "${DIR}/pre-execute_${ACADEMY_LANG}" ]] \
    && source "${DIR}/pre-execute_${ACADEMY_LANG}"

  # shellcheck disable=SC1090
  if [[ -f "${DIR}/execute_${ACADEMY_LANG}" ]]; then
    source "${DIR}/execute_${ACADEMY_LANG}"
  else
    if [[ -z "${ACADEMY_LANG}" ]]; then
      warning "Undefined ACADEMY_LANG variable. Execution skipped."
    else
      exception "Missing execute script 'execute_${ACADEMY_LANG}' for selected language."
    fi
  fi

  # shellcheck disable=SC1090
  [[ -f "${DIR}/post-execute_${ACADEMY_LANG}" ]] \
  && source "${DIR}/post-execute_${ACADEMY_LANG}"

  date +%s > "${GENERATED_TXT}"
  printf -- 'age: %s\n' "$(<"${GENERATED_TXT}")" >> "${BADGES_TXT}"
}

main "$@"
