#!/bin/bash

io_test_exit() {
  printf -- '%s' "${1}" >&2
  exit 1
}
pretty_diff() {
  diff --old-line-format=$'- %l\n' --new-line-format=$'+ %l\n' --unchanged-line-format='' "$@"
}
io_test() {
  declare -r test_folder="${1}"
  # shellcheck disable=SC2155
  declare -r test_folder_name="$(basename "${test_folder}")"
  declare -r test_name="${2}"
  declare -r test_path="${test_folder}/${test_name}"
  declare cmd="${IOTEST_CMD}"
  # TODO check unsupported test extensions (how?)
  echo -e "\nTest ${test_folder_name}/${test_name}"
  # create cmd from template
  # TODO: add reference to README
  declare -A variables
  # script varaibles
  variables=( \
   ['FOLDER_NAME']="${test_folder_name%.*}"\
   ['RELATIVE_PATH']="${test_folder#"${IOTEST_FOLDER}/"}"\
   ['WORKING_DIR']="${WORKING_DIR}" \
  )
  # add filtered env variables
  while read -r line; do
    [[ -z "${line}" ]] \
      && continue
    variables["$(cut -d= -f1 <<< "${line}")"]="$(cut -d= -f2- <<< "${line}")"
  done <<< "$(printenv | grep '^\(ACADEMY_\|CI_\)')"
  # replace variables in cmd
  for key in "${!variables[@]}"; do
    cmd="${cmd/@${key}@/${variables[${key}]}}"
  done
  # TODO use optarg file
  declare out_file err_file status_code
  out_file="$(mktemp)"
  err_file="$(mktemp)"
  # run cmd once
  if [[ -f "${test_path}.stdin" ]]; then
    eval "cat '${test_path}.stdin' | ${cmd} >'${out_file}' 2>'${err_file}'"
  else
    eval "${cmd} >'${out_file}' 2>'${err_file}'"
  fi
  status_code=$?
  declare retrun_code=0
  # test status code
  if [[ -f "${test_path}.sc" ]]; then
    echo 'Status code diff'
    pretty_diff <(echo "${status_code}") "${test_path}.sc" \
      || retrun_code=1
  fi
  # test stdout
  if [[ -f "${test_path}.stdout" ]]; then
    pretty_diff "${out_file}" "${test_path}.stdout" \
      || retrun_code=1
  fi
  # test stderr
  if [[ -f "${test_path}.stderr" ]]; then
    echo "Stderr diff"
    pretty_diff "${err_file}" "${test_path}.stderr" \
      || retrun_code=1
  fi
  rm "${out_file}"
  rm "${err_file}"
  return ${retrun_code}
}
run_io_tests() {
  [[ ! -d "${IOTEST_FOLDER}" ]] \
    && return
  # run iotests
  declare -i passed=0 count=0
  # search deepest folders only by -links 2 (folder with 2 hardlinks)
  while read -r -d '' folder; do
    # shellcheck disable=SC2012
    for name in $(ls "${folder}/" | rev | cut -d. -f2- | rev | sort -u); do
      count+=1
      io_test "${folder}" "${name}" \
        && passed+=1
    done
  done < <(find "${IOTEST_FOLDER}" -type d -links 2 -print0)
  # generate summary and badge
  printf -- "Summary: %s/%s\n" "${passed}" "${count}"
}
main() {
  [[ -n "${1}" ]] \
    || io_test_exit "Missing iotest folder"
  [[ -n "${2}" ]] \
    || io_test_exit "Missing iotest cmd"
  declare -r IOTEST_FOLDER="${1}"
  declare -r IOTEST_CMD="${2}"
  run_io_tests
}

main "$@"