#!/bin/bash
measure() {
  # shellcheck disable=SC2155
  [[ ! -t 0 ]] \
    || exception 'Missing stdin' 2
  exec 3<&0
  acquire_token
  # create output directory if not
  [[ -z "${OUTPUT_DIR}" ]] \
    && OUTPUT_DIR="$(mktemp -d)"
  # shellcheck disable=SC2013
  for user_name in $(cat <&3); do
    user_project_name="${PREFIX}${user_name}"
    user_project_ns="${NAMESPACE}/${user_project_name}"
    # shellcheck disable=SC2034
    user_project_id="$(get_project_id "${user_project_ns}")" \
      || continue
    [[ "${DRY_RUN}" == 'true' ]] \
      && continue
    mkdir -p "${OUTPUT_DIR}/${user_project_ns}"
    git_clone "$(get_remote_url "${user_project_ns}")" "${OUTPUT_DIR}/${user_project_ns}"
  done
  [[ "${DRY_RUN}" == 'true' ]] \
    && return
  # allow **/*
  shopt -s globstar
  declare -a basefiles
  for file in "${WORKING_DIR}"/src/main/**/*."${ACADEMY_LANG}"; do
    basefiles+=(-b "${file}")
  done
  # send projects into moss
  moss -l "${ACADEMY_LANG}" "${basefiles[@]}" -d "${OUTPUT_DIR}"/**/src/main/**/*."${ACADEMY_LANG}" \
    "${WORKING_DIR}"/src/main/**/*."${ACADEMY_LANG}"
}

declare -r ACADEMY_LANG='java'
declare IGNORE='false'
declare DRY_RUN='false'
declare PREFIX=''
declare NAMESPACE=''
declare OUTPUT_DIR=''

# get options
declare OPT
OPT="$(getopt --name "${0}" --options 'hinp:s:o:' \
  --longoptions 'ignore,dry-run,help,prefix:,namespace:,output-dir:' \
  -- "$@")" \
  && eval set -- "${OPT}" \
  || exit 1

# process options
while (( $# > 0 )); do
  # shellcheck disable=SC2034
  case "${1}" in
    -h|--help) print_usage && exit 0 ;;
    -i|--ignore) IGNORE='true'; shift ;;
    -n|--dry-run) DRY_RUN='true'; shift ;;
    -p|--prefix) PREFIX="${2}"; shift; shift ;;
    -s|--namespace) NAMESPACE="${2}"; shift; shift ;;
    -o|--output-dir)
      OUTPUT_DIR="${2}";
      [[ -d "${OUTPUT_DIR}" ]] \
        || mkdir -p "${OUTPUT_DIR}" \
        || exception "Unable to create '${OUTPUT_DIR}' directory"
      shift; shift ;;
    --) shift; break ;;
     *) break ;;
  esac
done

measure
