#!/bin/bash

# shellcheck disable=SC2034
# shellcheck disable=SC2155
declare -r SCRIPT_NAME="$(basename "${0}")"
# shellcheck disable=SC2034
declare -r TOKEN="${ACCESS_TOKEN}"

measure() {
  # shellcheck disable=SC2155
  declare -r pwd="$(pwd)"
  # shellcheck disable=SC2155
  declare -r user_projects_folder="$(mktemp -d)"
  # shellcheck disable=SC2155
  declare -r project_namespace="$(dirname "${pwd}" | cut -d/ -f3-)"

  # get all branches
  git fetch --all >/dev/null
  # for all branches get user projects
  declare user_projects_namespace
  declare user_projects
  declare group_id
  for branch in $(git branch -r | grep -v '\->'); do
    user_projects_namespace="${project_namespace}/$(basename "${branch}")"
    # get user_projects_namespace id
    group_id="$(get_group_id "${user_projects_namespace}")" \
      || exit 1
    [[ -z "${group_id}" ]] \
      && continue
    user_projects="$(get_group_projects)" \
      || eit 1
    # clone all user_projects from ns
    for user_project_ns in ${user_projects}; do
      mkdir -p "${user_projects_folder}/${user_project_ns}"
      git_clone "$(get_remote_url)" "${user_projects_folder}/{$user_project_ns}"
    done
  done

  # allow **/*
  shopt -s globstar

  # send projects into moss
  declare -r cam_lang='java'
  ./moss -l "${cam_lang}" -d "${user_projects_folder}"/**/src/main/**/*."${cam_lang}" src/main/**/*."${cam_lang}"
}

measure
