#!/bin/bash

echo "Post-collect: Gallery"

shopt -s globstar nullglob

declare -A themes=()

for dir in "${local_gallery}"/*/*; do
  dir="${dir#"${local_gallery}"/*/}"
  themes["${dir}"]=
done

themes_sorted=()
while read -r; do
  themes_sorted+=( "$REPLY" )
done < <( printf '%s\n' "${!themes[@]}" | sort )

for theme in "${themes_sorted[@]}"; do
  printf '## %s\n\n' "${theme//-/ }" >> "${readme}"
  for file in "${local_gallery}"/*/"${theme}"/*; do
    printf '![%s](%s){width=19%%}\n' "${file#"${local_gallery}"}" "${file#"${local_gallery}"}" >> "${readme}"
  done
  printf '\n\n' >> "${readme}"
done

cat "${readme}" >&2

# Add-commit-push galerii
git -C "${local_gallery}" remote -v
git -C "${local_gallery}" add .
git -C "${local_gallery}" commit -m "Update gallery"
git -C "${local_gallery}" push

# Clean-up
rm -rf "${local_gallery}"
rm -rf .collect
mkdir .collect
