#!/usr/bin/env bash

# shellcheck disable=SC2034
declare -r IOTEST_FOLDER="${WORKING_DIR}/iotest"
declare -r IOTEST_LOG="${RESULTS}/iotest.log"
declare -r IOTEST_TXT="${RESULTS}/iotest.txt"
declare -r IOTEST_SVG="${RESULTS}/iotest.svg"

# deafults for iotests
generate_badge 'IO Tests' '0/0'

printf -- 'n/a' > "${IOTEST_TXT}"
printf -- '' > "${IOTEST_LOG}"
