#!/usr/bin/env bash

if [[ -z "${ACADEMY_EDITABLE}" ]]; then
  echo "Missing ACADEMY_EDITABLE variable"
  exit 1
fi

set -x

# set url with token
declare git_url
git_url="https://project_${CI_PROJECT_ID}_bot:${ACADEMY_SUBMIT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
git remote set-url origin "${git_url}"
# update current repo
git fetch --all
git checkout --track origin/main
git checkout --track origin/source
git checkout --track origin/submit
git checkout submit
# update from source
git merge --strategy-option theirs source
# copy editable files
rm ${ACADEMY_EDITABLE}
git checkout main -- ${ACADEMY_EDITABLE}
# push to submit
git add .
git commit -am "Sync with source and main"
git push "${git_url}" submit
